### ISSUE TITLE
Adopt react-markdown?

### ISSUE THREAD

**Issue by rexxars** [remarkjs/governance#2]
Hi!

I'm the author of [react-markdown](https://github.com/rexxars/react-markdown). It's been fun, but I've gone into a bit of a maintainer burnout for the past year. Given that it's been powered by remark for a while now, I thought maybe the remark/unified collective might be interested in adopting it.

I still have strong feelings on the core direction of the project, and I'd like to be able to contribute and code on it, but without having the entire burden on my shoulders.

Would there be any interest in this? 

The project has over 570k downloads on npm per month and almost 6000 stars on GitHub, and has been a part of my life for almost 5 years now, so it is with mixed feelings and a heavy heart I propose this. But, it's probably the best course of action for the project.

**Comment by wooorm** [comment]
Sorry was a bit distracted with micromark work! As there are no objections, this is good to go! Can you add me as a maintainer on GitHub? That’s the easiest way for me to transfer the project into the remarkjs organization! And also add me on npm? tooling will kick in later to finalize everything.

Just to confirm: due to security reasons you’ll lose access to publish on npm or administer the repo on GH. You’ll still be able to push to master and merge PRs, but the more dangerous stuff is left for the group to decide and a small group of people to administer!

**Comment by rexxars** [comment]
Thanks! Invite sent for GitHub, and added as maintainer on npm.

**Comment by wooorm** [comment]
Sweet, thanks!

I’m sorry, I made a mistake! I can’t transfer the repo myself as a collaborator. Can you instead transfer ownership to me? Should be at the bottom here: https://github.com/rexxars/react-markdown/settings

**Comment by wooorm** [comment]
Nice, alright, tooling will kick in in 24hrs to update npm and github rights.

Is this project still sponsored by Sanity?

For next steps, I believe @ChristianMurphy has interest in working on react-markdown, however, he is moving currently, so a bit busy!

**Comment by ChristianMurphy** [comment]
Welcome the the unified/remark collective @rexxars!
We're glad to have you as a member.

I do have interest in helping to maintain react-markdown.
As @wooorm mentions I am in the process of moving, keeping things a bit busy at the moment, I should be able to invest more time in the coming weeks.

A few things which I'm interested in:
* clearing up the issue backlog, there are currently 133 open issues https://github.com/remarkjs/react-markdown/issues most of which appear to be questions that are already answered, and can be closed.
* Potentially moving future questions to GitHub discussions to break out questions from feature requests and bug reports
* potentially refactoring to use remark-rehype and remark-react, while this may raise the overall complexity. It would significantly reduce library level complexity, and offer a new extension point which appears to address many of the feature requests around new syntax.
* Potentially moving to native TypeScript, there seems to be a lot of TypeScript interest for the repository, moving to native TypeScript would keep the typings in sync with the code (alternatives include jsdoc based typescript or updating the existing d.ts file)

> strong feelings on the core direction of the project

I'd be interested to hear more on this, to help align contributions in a direction you'd be more comfortable with.

**Comment by rexxars** [comment]
Thanks for the welcome!
I'm at a company all-hands until wednesday, but I'll follow up soon 👍

**Comment by wooorm** [comment]
Released!
